#!/usr/bin/env pvpython
"""Render Design V0 OpenFOAM output with ParaView.

Run with:

    pvpython scripts/paraview_design_v0_render.py

The script saves a still image and camera-orbit frames. A separate lightweight
Python encoder can convert the frames into MP4 when OpenCV is available.
"""

from __future__ import annotations

import argparse
import math
import shutil
from pathlib import Path

from paraview.simple import (  # type: ignore
    ColorBy,
    CreateView,
    GetColorTransferFunction,
    GetOpacityTransferFunction,
    OpenDataFile,
    Render,
    ResetSession,
    SaveScreenshot,
    Show,
)


ROOT = Path(__file__).resolve().parents[1]
CASE_FILE = ROOT / "cases" / "design_v0" / "design_v0.foam"
OUT_DIR = ROOT / "results" / "openfoam_design_v0" / "paraview"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", type=Path, default=CASE_FILE)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    parser.add_argument("--frames", type=int, default=72)
    parser.add_argument("--width", type=int, default=1280)
    parser.add_argument("--height", type=int, default=720)
    parser.add_argument("--clean", action="store_true", default=True)
    return parser.parse_args()


def set_reader_arrays(reader) -> None:
    for attr, values in [
        ("MeshRegions", ["internalMesh"]),
        ("CellArrays", ["T", "U", "p", "phiE"]),
        ("PointArrays", ["T", "U", "p", "phiE"]),
    ]:
        if hasattr(reader, attr):
            try:
                setattr(reader, attr, values)
            except Exception:
                pass


def configure_view(case_file: Path, width: int, height: int):
    reader = OpenDataFile(str(case_file))
    set_reader_arrays(reader)

    view = CreateView("RenderView")
    view.ViewSize = [width, height]
    view.Background = [1.0, 1.0, 1.0]

    display = Show(reader, view)
    display.Representation = "Surface"
    try:
        ColorBy(display, ("CELLS", "T"))
        display.RescaleTransferFunctionToDataRange(True, False)
        display.SetScalarBarVisibility(view, True)
        lut = GetColorTransferFunction("T")
        lut.ApplyPreset("Viridis (matplotlib)", True)
        GetOpacityTransferFunction("T")
    except Exception:
        display.DiffuseColor = [0.1, 0.3, 0.8]

    view.ResetCamera(False)
    camera = view.GetActiveCamera()
    camera.SetFocalPoint(0.0, 0.0, 2.5e-5)
    camera.SetPosition(0.0, -0.0045, 0.0032)
    camera.SetViewUp(0.0, 0.0, 1.0)
    view.StillRender()
    return view, camera


def render_orbit(view, camera, out_dir: Path, frame_count: int, width: int, height: int) -> None:
    frame_dir = out_dir / "frames"
    frame_dir.mkdir(parents=True, exist_ok=True)
    radius = 0.0045
    z = 0.0032
    focal = (0.0, 0.0, 2.5e-5)

    for frame in range(frame_count):
        angle = 2.0 * math.pi * frame / frame_count
        camera.SetFocalPoint(*focal)
        camera.SetPosition(radius * math.sin(angle), -radius * math.cos(angle), z)
        camera.SetViewUp(0.0, 0.0, 1.0)
        Render(view)
        SaveScreenshot(
            str(frame_dir / f"frame_{frame:04d}.png"),
            view,
            ImageResolution=[width, height],
        )


def main() -> int:
    args = parse_args()
    if not args.case.exists():
        raise FileNotFoundError(args.case)
    if args.clean and args.out_dir.exists():
        shutil.rmtree(args.out_dir)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    ResetSession()
    view, camera = configure_view(args.case, args.width, args.height)
    SaveScreenshot(
        str(args.out_dir / "design_v0_potential_still.png"),
        view,
        ImageResolution=[args.width, args.height],
    )
    render_orbit(view, camera, args.out_dir, args.frames, args.width, args.height)
    (args.out_dir / "README.md").write_text(
        "Generated by scripts/paraview_design_v0_render.py.\n"
        "Still image: design_v0_potential_still.png\n"
        "Orbit frames: frames/frame_*.png\n",
        encoding="utf-8",
    )
    print(f"Rendered ParaView still and {args.frames} frames to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
